### ISSUE TITLE
4.3 section LUMP codes in mixup.py seems didn't run ?

### ISSUE THREAD

**Issue by qwtoe** [divyam3897/UCL#5]
i run the first command line in README，find didn't use LUMP part in the whole train, did i miss something ??

**Comment by divyam3897** [comment]
Hi,

The model configuration's default setting is ```finetune```. To execute LUMP, you must modify the config model to ```mixup```.

**Comment by qwtoe** [comment]
Hi, thanks for your reply ！ @divyam3897
